apiVersion: v1
kind: ConfigMap
metadata:
  name: spinywheely-config
  namespace: spinywheely
data:
  NODE_ENV: production
  PORT: "3000"
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: spinywheely
  DATABASE_USER: spinywheely
  DATABASE_POOL_MAX: "10"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
